#!/usr/bin/env bash

LOCKFILE=/tmp/sway.lock

if [ -f $LOCKFILE ]
then
  echo 'swaylock already running'
  exit 0
fi

swaylock -f -i "/home/$USER/Pictures/Backgrounds/Starship\ and\ Super\ Heavy\ Stack.jpg" --font "Source Code Pro" --scaling fill
exit 0

swaylock -f -i "/home/$USER/Pictures/Backgrounds/wallhaven-zm9zwo.png" --font "Source Code Pro" --scaling fill
exit 0

# handle being called from systemd service
if [ -z "$XDG_RUNTIME_DIR" ] && [ -z "$SWAYSOCK" ]
then
  if [ -z "$USER" ]
  then
    # Horrible hack
    USER=ggreer
  fi
  uid=$(id -u "$USER")
  export XDG_RUNTIME_DIR="/run/user/$uid/"
  SWAYSOCK=$(find "$XDG_RUNTIME_DIR" -maxdepth 1 -iname "sway*sock")
  export SWAYSOCK
fi

#if [ -z "$DISPLAY" ]
#then
  # Horrible hack in case we lack this env var
#  export DISPLAY=:0
#fi

LOCK_IMG=/home/$USER/lockscreen.png
grim "$LOCK_IMG" && \
#convert -blur 0x10 "$LOCK_IMG" "$LOCK_IMG" && \
# convert -scale 12.5% -scale 800% "$LOCK_IMG" "$LOCK_IMG" && \
convert -scale 5% -scale 2000% "$LOCK_IMG" "$LOCK_IMG" && \
touch $LOCKFILE
# swaylock -c 000000
# -u == hide lock feedback
#swaylock -u -i "$LOCK_IMG" --font ProggyTinyTTSZ --scaling fill
swaylock -f -i "$LOCK_IMG" --font "Source Code Pro" --scaling fill
rm $LOCKFILE
