#!/usr/bin/env bash

# handle being called from systemd service
if [ -z "$XDG_RUNTIME_DIR" ] && [ -z "$SWAYSOCK" ]
then
  uid=$(id -u "$USER")
  export XDG_RUNTIME_DIR="/run/user/$uid/"
  SWAYSOCK=$(find "$XDG_RUNTIME_DIR" -iname "sway*sock")
  export SWAYSOCK
fi

LOCK_IMG=/home/$USER/lockscreen.png
swaygrab "$LOCK_IMG" && \
#convert -blur 0x10 "$LOCK_IMG" "$LOCK_IMG" && \
convert -scale 10% -scale 1000% "$LOCK_IMG" "$LOCK_IMG" && \
# convert -scale 5% -scale 2000% "$LOCK_IMG" "$LOCK_IMG" && \
swaylock -u -i "$LOCK_IMG" --font ProggyTinyTTSZ
