#!/usr/bin/env bash

LOCKFILE=/tmp/sway.lock

if [ -f $LOCKFILE ]
then
  echo 'swaylock already running'
  exit 0
fi

# handle being called from systemd service
if [ -z "$XDG_RUNTIME_DIR" ] && [ -z "$SWAYSOCK" ]
then
  uid=$(id -u "$USER")
  export XDG_RUNTIME_DIR="/run/user/$uid/"
  SWAYSOCK=$(find "$XDG_RUNTIME_DIR" -iname "sway*sock")
  export SWAYSOCK
fi

LOCK_IMG=/home/$USER/lockscreen.png
swaygrab "$LOCK_IMG" && \
#convert -blur 0x10 "$LOCK_IMG" "$LOCK_IMG" && \
convert -scale 12.5% -scale 800% "$LOCK_IMG" "$LOCK_IMG" && \
# convert -scale 5% -scale 2000% "$LOCK_IMG" "$LOCK_IMG" && \
touch $LOCKFILE
swaylock -u -i "$LOCK_IMG" --font ProggyTinyTTSZ --scaling fill
rm $LOCKFILE
